services:
  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: dev.Dockerfile
    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src/app:/src/app
      - ./public:/app/public
    restart: always
    # ports:
    #   - 3000:3000
    networks:
      - my_network
    depends_on:
      db:
        condition: service_started

  nginx: 
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - my_network
    depends_on:
      - next-app
      
  db:
    image: postgres:latest
    env_file:
      - .env
    # ports:
    #   - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

networks:
  my_network:
    external: true

volumes:
  postgres_data: